# Generated by Django 4.2.20 on 2025-05-26 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_bio_user_nickname_userlinks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlinks',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_links', to=settings.AUTH_USER_MODEL),
        ),
    ]
