# Generated by Django 4.2.20 on 2025-05-19 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oauthclient',
            options={'permissions': [('oauth_active', 'Can use oauth features')]},
        ),
        migrations.AlterField(
            model_name='oauthclient',
            name='status',
            field=models.CharField(choices=[('DEV', 'Development'), ('PROD', 'Production'), ('DEL', 'Deleted')], default='DEV', max_length=8),
        ),
    ]
