# Generated by Django 4.2.20 on 2025-05-20 08:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oauth', '0002_alter_oauthclient_options_alter_oauthclient_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauthclient',
            name='test_users',
            field=models.ManyToManyField(related_name='is_tester_of', to=settings.AUTH_USER_MODEL),
        ),
    ]
