# Generated by Django 4.2.20 on 2025-05-20 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0003_oauthclient_test_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callbackurl',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='callback_urls', to='oauth.oauthclient'),
        ),
    ]
