# Generated by Django 4.2.20 on 2025-05-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0004_alter_callbackurl_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callbackurl',
            name='url',
            field=models.URLField(max_length=256, unique=True),
        ),
    ]
