# Generated by Django 4.2.20 on 2025-05-26 07:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oauth', '0005_alter_callbackurl_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauthclient',
            name='users',
            field=models.ManyToManyField(related_name='using_apps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='callbackurl',
            name='url',
            field=models.URLField(max_length=256),
        ),
        migrations.AddConstraint(
            model_name='callbackurl',
            constraint=models.UniqueConstraint(fields=('client', 'url'), name='unique_url_per_client'),
        ),
    ]
