# Generated by Django 4.2.20 on 2025-05-26 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oauth', '0006_oauthclient_users_alter_callbackurl_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauthclient',
            name='desc',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='oauthclient',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_apps', to=settings.AUTH_USER_MODEL),
        ),
    ]
