# Generated by Django 4.2.20 on 2025-05-27 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0007_oauthclient_desc_alter_oauthclient_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauthclient',
            name='entrypoint',
            field=models.URLField(max_length=256, null=True),
        ),
    ]
