# Generated by Django 4.2.20 on 2025-05-27 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0008_oauthclient_entrypoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauthclient',
            name='status',
            field=models.CharField(choices=[('DEV', 'Development'), ('PROD', 'Production'), ('REV', 'Under Review'), ('REJ', 'Rejected'), ('CLO', 'Closed'), ('DEL', 'Deleted')], default='DEV', max_length=8),
        ),
    ]
