# Generated by Django 4.2.20 on 2025-06-10 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0009_alter_oauthclient_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauthclient',
            name='logo',
            field=models.ImageField(max_length=256, null=True, upload_to=''),
        ),
    ]
